#!/bin/bash

dir=$HOME/dotfiles
olddir=$HOME/dotfiles_old
files="
digrc
gemrc
gitconfig
gitignore
shell_aliases
zshenv
zprofile
zshrc
"


# create dotfiles_old
echo "--Creating $olddir for backup of any existing dotfiles"
mkdir -p $olddir

# change to the dotfiles directory
echo "--Changing to the $dir directory"
cd $dir


# move any existing dotfiles in homedir to dotfiles_old directory, then create symlinks from the homedir to any files in the ~/dotfiles directory specified in $files
for file in $files; do
  echo "----Moving any existing dotfiles from $HOME to $olddir"
  mv $HOME/.$file $olddir
  echo "----Creating symlink to $file in home directory."
  ln -s $dir/$file ~/.$file
done

## bash git prompt
ln -s $HOME/dotfiles/Tatum.bgptheme /usr/local/opt/bash-git-prompt/share/themes/
